version: '3.8'

services:
  database:
    container_name: postgres-webflux-example
    image: postgres:latest
    ports:
    - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'EXAMPLE'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./postgres-init-files:/docker-entrypoint-initdb.d

volumes:
  postgres-data: